name: Shit

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: check Windows version
      run: winver
    - name: install sshserver
      run: dism /Online /Add-Capability /CapabilityName:OpenSSH.Server~~~~0.0.1.0
    - name: check ssh server
      run: Get-WindowsCapability -Online | ? Name -like 'OpenSSH.Server*'
    - name: check ssh
      run: Get-Service -Name *ssh*
    - name: set ssh service automatic
      run: |
            Set-Service -Name 'ssh-agent' -StartupType 'Automatic'
            Set-Service -Name sshd -StartupType 'Automatic'
    - name: start sshd, ssh-agent
      run: |
            Start-Service sshd
            Start-Service 'ssh-agent'
    - name: check ssh service
      run: Get-Service -Name *ssh*
    - name: GetIp
      run: Get-NetIPAddress
    - name: install zrok
      run: Invoke-WebRequest https://github.com/openziti/zrok/releases/download/v0.4.39/zrok_0.4.39_windows_amd64.tar.gz
    - name: extract zip
      run: |
            New-Item -Path "$env:TEMP\zrok" -ItemType Directory -ErrorAction Stop
            tar -xf .\zrok*windows*.tar.gz -C "$env:TEMP\zrok"
    - name: set up zrok
      run: |
            $source = Join-Path -Path $env:TEMP -ChildPath "zrok\zrok.exe"
            $destination = Join-Path -Path $env:USERPROFILE -ChildPath "bin\zrok.exe"
            New-Item -Path $destination -ItemType Directory -ErrorAction SilentlyContinue
            Copy-Item -Path $source -Destination $destination
            $env:path += ";"+$destination
    - name: run zrok
      run: zrok version
    - uses: actions/checkout@v4
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
    - name: set firewall for ssh
      run: |
            ssh -R 6769:localhost:3389 serveo.net -vvv
            
