name: Shit

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - name: check Windows version
      run: winver
    - name: install sshserver
      run: dism /Online /Add-Capability /CapabilityName:OpenSSH.Server~~~~0.0.1.0
    - name: check ssh server
      run: Get-WindowsCapability -Online | ? Name -like 'OpenSSH.Server*'
    - name: check ssh
      run: Get-Service -Name *ssh*
    - name: start ssh service
      run: |
            Start-Service sshd
            Set-Service -Name sshd -StartupType 'Automatic'
    - run: Set-Service -Name 'ssh-agent' -StartupType 'Automatic'
    - run: Start-Service 'ssh-agent'
    - name: check ssh service
      run: Get-Service -Name *ssh*
